# Unittests for PACKAGE_NAME
#
# Notes:
#   - Uncomment evertything below these notes to enable workflow.
#   - `timeout-minutes` may need to be updated depanding on how long the tests should take.
#   - Additional environments can be defined in the ./ci/ directory and added to the `environment-file` list.
#   - Swap PACKAGE_NAME for the actual package name.
#   - Codecov must be enabled for the repo.
#   - Within the project repo, navigate to Setting/Secrets to set `secrets.CODECOV_TOKEN`.
#
# -------------------------------------------------------

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '59 11 * * *'

jobs:
  unittests:
    name: conda (${{ matrix.os }}, ${{ matrix.environment-file }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
        environment-file: [ci/36.yaml, ci/37.yaml, ci/38.yaml]
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           miniconda-version: 'latest'
           auto-update-conda: true
           auto-activate-base: false
           environment-file: ${{ matrix.environment-file }}
           activate-environment: test
      - shell: bash -l {0}
        run: conda info --all
      - shell: bash -l {0}
        run: conda list
      - shell: bash -l {0}
        run: py.test -v PACKAGE_NAME --cov=PACKAGE_NAME --cov-report=xml
      - name: codecov (${{ matrix.os }}, ${{ matrix.environment-file }})
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: PACKAGE_NAME-codecov
